services:
  db:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: gallerydb
      POSTGRES_USER: galleryuser
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: my_django
    restart: always
    volumes:
      - .:/app
    environment:
      DB_NAME: gallerydb
      DB_USER: galleryuser
      DB_PASSWORD: supersecret
      DB_HOST: db
      DB_PORT: 5432
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: my_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - static_volume:/app/src/staticfiles
      - media_volume:/app/src/media
    depends_on:
      - web

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/usbdrive/docker-volumes/postgres
      o: bind

  static_volume:
    driver: local
    driver_opts:
      type: none
      device: /mnt/usbdrive/docker-volumes/static
      o: bind

  media_volume:
    driver: local
    driver_opts:
      type: none
      device: /mnt/usbdrive/docker-volumes/media
      o: bind