services:
  db:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: my_django
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/src/staticfiles
      - media_volume:/app/src/media
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: ${DEBUG}
      DJANGO_SK: ${DJANGO_SECRET_KEY}
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: my_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/dev/:/etc/nginx/conf.d
      - static_volume:/app/src/staticfiles
      - media_volume:/app/src/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
