# Generated by Django 5.2.6 on 2025-09-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_tag_cardtag_card_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='template_name',
            field=models.CharField(default='Gallery/Cards/card_default', max_length=200),
        ),
    ]
